spring:
  config:
    activate:
      on-profile: "datasource"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:board}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}