spring:
  config:
    activate:
      on-profile: dev

  # H2
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: embedded
      schema-locations: classpath:schema.sql
      encoding: UTF-8
      platform: h2

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

  batch:
    jdbc:
      initialize-schema: always

jwt:
  header: token
  issuer: programmers
  client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
  expiry-seconds: 3600

