spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board_jpa
    username: root
    password : dudwl0804!
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

#---
#spring:
#  config:
#    activate:
#      on-profile: test
#
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test2;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;
#    username: sa
#    password:
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
#      dialect: org.hibernate.dialect.H2Dialect
#    database: h2